# Generated by Django 5.2.5 on 2025-08-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
    ]
