# Generated by Django 5.2.5 on 2025-09-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_userdata_contact_remove_userdata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
