# Generated by Django 5.2.5 on 2025-09-19 10:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_userdata_category_alter_userdata_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
